sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123

  redis:
    host: localhost
    port: 6379
    database: 0

  # 阿里云OSS配置
  alioss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: winter-java
    region: cn-hangzhou
    custom-domain: https://oss.haoea.xyz
